from langchain_google_genai import ChatGoogleGenerativeAI

def find_tool_based_on_query(user_query):
    # Prepare the input for Gemini
    keyword_list = ', '.join(keyword_tool_map.keys())  # Create a comma-separated string of keywords
    prompt = f"Given the user query: '{user_query}', determine the appropriate keyword from the following list: {keyword_list}. Return only the keyword."

    # Call Gemini to analyze the query
    response = llm.invoke(prompt)  # Pass the prompt as a string directly

    # Print the response for debugging
    print("Response from Gemini: ", response)

    # Extract the keyword from the Gemini response
    selected_keyword = response.content.strip()
    if selected_keyword[0]=="*":
        selected_keyword=selected_keyword[1:-1]
    print("Tool being used: ", keyword_tool_map[selected_keyword])
    
    # Check if the selected keyword exists in the keyword_tool_map
    if selected_keyword in keyword_tool_map:
        return keyword_tool_map[selected_keyword]  # Return the associated tool name

    # If no keyword matches, return None
    return None

# Keyword-to-Tool Mapping
llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0.2,
    max_tokens=None,
    timeout=None,
    max_retries=2,
    google_api_key="AIzaSyDIG-JhAjoTJPZV_M5CGzjhIX8klNbXm3I"
)
keyword_tool_map = {
    # check_divisions
    "doj divisions": "check_divisions",
    "department of justice divisions": "check_divisions",
    "divisions information": "check_divisions",
    "doj organizational structure": "check_divisions",
    "departmental responsibilities": "check_divisions",
    "doj structure": "check_divisions",
    "justice department organization": "check_divisions",
    "doj departments": "check_divisions",
    "justice ministry divisions": "check_divisions",
    "doj offices": "check_divisions",
    "doj bureaus": "check_divisions",
    "department of justice organization chart": "check_divisions",
    "doj hierarchy": "check_divisions",
    "justice department units": "check_divisions",
    "doj administrative divisions": "check_divisions",
    "department of justice sections": "check_divisions",
    "doj branch information": "check_divisions",
    "justice department structure": "check_divisions",
    "doj organizational chart": "check_divisions",
    "department of justice branches": "check_divisions",
    "justice divisions": "check_divisions",
    "divisional roles": "check_divisions",
    "subdivisions of doj": "check_divisions",
    "doj structural overview": "check_divisions",
    "functions of divisions": "check_divisions",
    # get_judicial_infrastructure_scheme
    "judicial infrastructure schemes": "get_judicial_infrastructure_scheme",
    "court infrastructure upgrades": "get_judicial_infrastructure_scheme",
    "judicial infrastructure projects": "get_judicial_infrastructure_scheme",
    "infrastructure development in judiciary": "get_judicial_infrastructure_scheme",
    "court modernization plans": "get_judicial_infrastructure_scheme",
    "judiciary facilities improvement": "get_judicial_infrastructure_scheme",
    "court building projects": "get_judicial_infrastructure_scheme",
    "judicial system upgrades": "get_judicial_infrastructure_scheme",
    "court renovation schemes": "get_judicial_infrastructure_scheme",
    "judiciary infrastructure funding": "get_judicial_infrastructure_scheme",
    "court facilities enhancement": "get_judicial_infrastructure_scheme",
    "judicial premises development": "get_judicial_infrastructure_scheme",
    "court construction projects": "get_judicial_infrastructure_scheme",
    "judiciary modernization schemes": "get_judicial_infrastructure_scheme",
    "court infrastructure plans": "get_judicial_infrastructure_scheme",
    "judicial buildings improvement": "get_judicial_infrastructure_scheme",
    "court premises upgrade": "get_judicial_infrastructure_scheme",
    "judiciary infrastructure initiatives": "get_judicial_infrastructure_scheme",
    "court facilities modernization": "get_judicial_infrastructure_scheme",
    "judicial system infrastructure": "get_judicial_infrastructure_scheme",
    "court improvements": "get_judicial_infrastructure_scheme",
    "judicial facilities": "get_judicial_infrastructure_scheme",
    "infrastructure funding for courts": "get_judicial_infrastructure_scheme",
    "court infrastructure goals": "get_judicial_infrastructure_scheme",

    # get_doj_functions_responsibilities
    "doj activities": "get_doj_functions_responsibilities",
    "roles of doj": "get_doj_functions_responsibilities",
    "functions of the doj": "get_doj_functions_responsibilities",
    "doj responsibilities": "get_doj_functions_responsibilities",
    "department of justice functions": "get_doj_functions_responsibilities",
    "doj key activities": "get_doj_functions_responsibilities",
    "doj policy making": "get_doj_functions_responsibilities",
    "doj legal reforms": "get_doj_functions_responsibilities",
    "judiciary appointments": "get_doj_functions_responsibilities",
    "doj duties": "get_doj_functions_responsibilities",
    "justice department roles": "get_doj_functions_responsibilities",
    "doj main tasks": "get_doj_functions_responsibilities",
    "department of justice obligations": "get_doj_functions_responsibilities",
    "doj core functions": "get_doj_functions_responsibilities",
    "justice ministry duties": "get_doj_functions_responsibilities",
    "doj primary responsibilities": "get_doj_functions_responsibilities",
    "department of justice key roles": "get_doj_functions_responsibilities",
    "doj mandates": "get_doj_functions_responsibilities",
    "justice department assignments": "get_doj_functions_responsibilities",
    "doj operational functions": "get_doj_functions_responsibilities",
    "department of justice tasks": "get_doj_functions_responsibilities",
    "doj mission and functions": "get_doj_functions_responsibilities",
    "justice ministry responsibilities": "get_doj_functions_responsibilities",
    # check_case_with_CNR
    "case status by CNR": "check_case_with_CNR",
    "find case by CNR": "check_case_with_CNR",
    "track case by CNR number": "check_case_with_CNR",
    "case information by CNR number": "check_case_with_CNR",
    "case details using CNR": "check_case_with_CNR",
    "CNR case search": "check_case_with_CNR",
    "case status search by CNR": "check_case_with_CNR",
    "CNR number lookup": "check_case_with_CNR",
    "check CNR case status": "check_case_with_CNR",
    "track case status with CNR": "check_case_with_CNR",
    "find case details by CNR": "check_case_with_CNR",
    "get case status using CNR": "check_case_with_CNR",
    "CNR case tracking": "check_case_with_CNR",
    "search case details by CNR number": "check_case_with_CNR",
    "search case by CNR number": "check_case_with_CNR",
    "track case using CNR number": "check_case_with_CNR",
    "check legal case with CNR": "check_case_with_CNR",
    "CNR case info": "check_case_with_CNR",
    "find legal case by CNR": "check_case_with_CNR",
    "legal case search by CNR": "check_case_with_CNR",
    "track legal case status by CNR": "check_case_with_CNR",
    "check case information using CNR": "check_case_with_CNR",
    # get_free_legal_aid_info
    "free legal support": "get_free_legal_aid_info",
    "legal aid options": "get_free_legal_aid_info",
    "free legal aid services": "get_free_legal_aid_info",
    "legal aid eligibility": "get_free_legal_aid_info",
    "free legal advice": "get_free_legal_aid_info",
    "legal aid centers": "get_free_legal_aid_info",
    "legal awareness programs": "get_free_legal_aid_info",
    "lok adalats": "get_free_legal_aid_info",
    "grant-in-aid schemes": "get_free_legal_aid_info",
    "pro bono legal services": "get_free_legal_aid_info",
    "free legal representation": "get_free_legal_aid_info",
    "legal assistance for underprivileged": "get_free_legal_aid_info",
    "government-funded legal help": "get_free_legal_aid_info",
    "legal aid clinics": "get_free_legal_aid_info",
    "free legal consultation": "get_free_legal_aid_info",
    "legal aid for poor": "get_free_legal_aid_info",
    "community legal services": "get_free_legal_aid_info",
    "legal aid camps": "get_free_legal_aid_info",
    "free lawyer services": "get_free_legal_aid_info",
    "legal aid society": "get_free_legal_aid_info",
    "legal assistance programs": "get_free_legal_aid_info",
    "public interest litigation support": "get_free_legal_aid_info",

    # get_case_resolution_time
    "average time for cases": "get_case_resolution_time",
    "case processing duration": "get_case_resolution_time",
    "case resolution times": "get_case_resolution_time",
    "average case resolution time": "get_case_resolution_time",
    "case disposal times": "get_case_resolution_time",
    "judicial efficiency": "get_case_resolution_time",
    "court case duration": "get_case_resolution_time",
    "legal proceedings timeline": "get_case_resolution_time",
    "case closure periods": "get_case_resolution_time",
    "litigation timeframes": "get_case_resolution_time",
    "lawsuit resolution speed": "get_case_resolution_time",
    "court case length": "get_case_resolution_time",
    "legal case timelines": "get_case_resolution_time",
    "judiciary processing times": "get_case_resolution_time",
    "case adjudication duration": "get_case_resolution_time",
    "court efficiency metrics": "get_case_resolution_time",
    "legal matter resolution periods": "get_case_resolution_time",
    "case settlement timeframes": "get_case_resolution_time",
    "judicial process duration": "get_case_resolution_time",
    "court case turnaround time": "get_case_resolution_time",
    "legal dispute resolution speed": "get_case_resolution_time",
    "case conclusion timelines": "get_case_resolution_time",

    # get_disposal_last_month_cases
    "recently resolved cases": "get_disposal_last_month_cases",
    "case closure last month": "get_disposal_last_month_cases",
    "disposal statistics": "get_disposal_last_month_cases",
    "cases disposed of last month": "get_disposal_last_month_cases",
    "last month case disposal statistics": "get_disposal_last_month_cases",
    "resolved cases last month": "get_disposal_last_month_cases",
    "monthly case closure data": "get_disposal_last_month_cases",
    "recent case disposal figures": "get_disposal_last_month_cases",
    "court clearance rates last month": "get_disposal_last_month_cases",
    "judicial disposal statistics": "get_disposal_last_month_cases",
    "last month's resolved legal matters": "get_disposal_last_month_cases",
    "case conclusion numbers": "get_disposal_last_month_cases",
    "monthly court case resolutions": "get_disposal_last_month_cases",
    "recent legal case disposals": "get_disposal_last_month_cases",
    "last month's court efficiency data": "get_disposal_last_month_cases",
    "judiciary performance last month": "get_disposal_last_month_cases",
    "case closure statistics": "get_disposal_last_month_cases",
    "monthly legal matter resolutions": "get_disposal_last_month_cases",
    "court case completion rates": "get_disposal_last_month_cases",
    "recent judicial disposal figures": "get_disposal_last_month_cases",
    "last month's case clearance data": "get_disposal_last_month_cases",
    "monthly litigation conclusion stats": "get_disposal_last_month_cases",
    "recent court case disposal numbers": "get_disposal_last_month_cases",

    # get_instituted_last_month_cases
    "cases instituted last month": "get_instituted_last_month_cases",
    "new cases last month": "get_instituted_last_month_cases",
    "monthly new case filings": "get_instituted_last_month_cases",
    "recent court case initiations": "get_instituted_last_month_cases",
    "last month's legal proceedings started": "get_instituted_last_month_cases",
    "newly filed lawsuits statistics": "get_instituted_last_month_cases",
    "monthly case registration data": "get_instituted_last_month_cases",
    "recent litigation commencements": "get_instituted_last_month_cases",
    "court docket additions last month": "get_instituted_last_month_cases",
    "new legal matters last month": "get_instituted_last_month_cases",
    "monthly case inception figures": "get_instituted_last_month_cases",
    "recent judicial filings data": "get_instituted_last_month_cases",
    "last month's new court proceedings": "get_instituted_last_month_cases",
    "newly instituted legal actions": "get_instituted_last_month_cases",
    "monthly case initiation statistics": "get_instituted_last_month_cases",
    "recent lawsuit filings": "get_instituted_last_month_cases",
    "court case starts last month": "get_instituted_last_month_cases",
    "new legal disputes registered": "get_instituted_last_month_cases",
    "monthly litigation initiations": "get_instituted_last_month_cases",
    "recent case commencement data": "get_instituted_last_month_cases",

    # get_instituted_current_year_cases
    "cases instituted this year": "get_instituted_current_year_cases",
    "new cases this year": "get_instituted_current_year_cases",
    "yearly new case filings": "get_instituted_current_year_cases",
    "current year legal proceedings initiated": "get_instituted_current_year_cases",
    "annual case registration statistics": "get_instituted_current_year_cases",
    "this year's court docket additions": "get_instituted_current_year_cases",
    "yearly litigation commencements": "get_instituted_current_year_cases",
    "new lawsuits filed this year": "get_instituted_current_year_cases",
    "annual legal matter initiations": "get_instituted_current_year_cases",
    "current year judicial filings data": "get_instituted_current_year_cases",
    "yearly case inception figures": "get_instituted_current_year_cases",
    "this year's new court proceedings": "get_instituted_current_year_cases",
    "annual case initiation statistics": "get_instituted_current_year_cases",
    "current year litigation starts": "get_instituted_current_year_cases",
    "yearly new legal disputes registered": "get_instituted_current_year_cases",
    "this year's court case initiations": "get_instituted_current_year_cases",
    "annual legal action commencements": "get_instituted_current_year_cases",
    "current year case filing data": "get_instituted_current_year_cases",
    "yearly new court case statistics": "get_instituted_current_year_cases",
    "this year's instituted legal matters": "get_instituted_current_year_cases",
    "cases instituted this month": "get_instituted_current_year_cases",


    # get_coram_wise_pending_cases
    "pending cases by coram": "get_coram_wise_pending_cases",
    "coram-wise pending cases": "get_coram_wise_pending_cases",
    "cases pending before specific judges": "get_coram_wise_pending_cases",
    "judge-wise case backlog": "get_coram_wise_pending_cases",
    "pending litigation by judicial bench": "get_coram_wise_pending_cases",
    "court-wise case pendency": "get_coram_wise_pending_cases",
    "unresolved cases by coram": "get_coram_wise_pending_cases",
    "judicial backlog by bench": "get_coram_wise_pending_cases",
    "coram-specific case delays": "get_coram_wise_pending_cases",
    "pending matters before judges": "get_coram_wise_pending_cases",
    "judge-specific case pendency": "get_coram_wise_pending_cases",
    "court backlog by judicial panel": "get_coram_wise_pending_cases",
    "unfinished cases per coram": "get_coram_wise_pending_cases",
    "judicial workload by bench": "get_coram_wise_pending_cases",
    "coram-based case accumulation": "get_coram_wise_pending_cases",
    "pending litigation per judge": "get_coram_wise_pending_cases",
    "bench-wise unresolved cases": "get_coram_wise_pending_cases",
    "judicial pendency statistics": "get_coram_wise_pending_cases",
    "case backlog by court composition": "get_coram_wise_pending_cases",
    "coram-specific pending matters": "get_coram_wise_pending_cases",

    # get_cases_info
    "case information": "get_cases_info",
    "case details": "get_cases_info",
    "case status": "get_cases_info",
    "ongoing cases": "get_cases_info",
    "legal case updates": "get_cases_info",
    "court case information": "get_cases_info",
    "litigation details": "get_cases_info",
    "case progress reports": "get_cases_info",
    "legal matter status": "get_cases_info",
    "active court cases": "get_cases_info",
    "case proceedings information": "get_cases_info",
    "lawsuit details": "get_cases_info",
    "judicial case updates": "get_cases_info",
    "legal dispute information": "get_cases_info",
    "case file details": "get_cases_info",
    "court proceeding status": "get_cases_info",
    "current case information": "get_cases_info",
    "legal matter details": "get_cases_info",
    "case hearing updates": "get_cases_info",
    "litigation status reports": "get_cases_info",

    # get_cases_info
    "assistant counsel information": "get_cases_info",
    "assistant counsel duties": "get_cases_info",
    "pending civil cases": "get_cases_info",
    "pending criminal cases": "get_cases_info",
    "ac responsibilities": "get_cases_info",
    "assistant counsel roles": "get_cases_info",
    "ac case assignments": "get_cases_info",
    "assistant legal counsel info": "get_cases_info",
    "ac workload details": "get_cases_info",
    "assistant counsel case management": "get_cases_info",
    "ac legal support information": "get_cases_info",
    "assistant counsel performance metrics": "get_cases_info",
    "ac case resolution stats": "get_cases_info",
    "assistant counsel expertise areas": "get_cases_info",
    "ac litigation support details": "get_cases_info",
        # get_case_statistics
    "case statistics": "get_case_statistics",
    "general case statistics": "get_case_statistics",
    "overall case statistics": "get_case_statistics",
    "judicial case trends": "get_case_statistics",
    "court case data": "get_case_statistics",
    "legal proceedings statistics": "get_case_statistics",
    "case filing trends": "get_case_statistics",
    "litigation statistics": "get_case_statistics",
    "judicial system metrics": "get_case_statistics",
    "case resolution data": "get_case_statistics",
    "court performance statistics": "get_case_statistics",
    "legal case analytics": "get_case_statistics",
    "case disposition trends": "get_case_statistics",
    "judicial workload statistics": "get_case_statistics",
    "case type distribution": "get_case_statistics",
    "court efficiency metrics": "get_case_statistics",
    "legal matter statistics": "get_case_statistics",
    "case outcome trends": "get_case_statistics",
    "judicial caseload data": "get_case_statistics",
    "litigation trend analysis": "get_case_statistics",

    # get_traffic_violation_payments
    "traffic violation payments": "get_traffic_violation_payments",
    "traffic fine payment procedures": "get_traffic_violation_payments",
    "traffic fine payment": "get_traffic_violation_payments",
    "paying traffic fines": "get_traffic_violation_payments",
    "traffic fine dispute": "get_traffic_violation_payments",
    "online traffic ticket payment": "get_traffic_violation_payments",
    "traffic penalty settlement": "get_traffic_violation_payments",
    "traffic violation fee payment": "get_traffic_violation_payments",
    "resolving traffic tickets": "get_traffic_violation_payments",
    "traffic infraction payments": "get_traffic_violation_payments",
    "traffic citation fee settlement": "get_traffic_violation_payments",
    "traffic violation resolution": "get_traffic_violation_payments",
    "traffic ticket fine payment": "get_traffic_violation_payments",
    "settling traffic violations": "get_traffic_violation_payments",
    "traffic law infringement payments": "get_traffic_violation_payments",
    "traffic offense penalty payment": "get_traffic_violation_payments",
    "traffic violation fine processing": "get_traffic_violation_payments",
    "traffic ticket resolution methods": "get_traffic_violation_payments",
    "traffic violation fee settlement": "get_traffic_violation_payments",
    "traffic fine payment options": "get_traffic_violation_payments",

    # get_judicial_system_and_vacancies
    "judicial system": "get_judicial_system_and_vacancies",
    "judicial vacancies": "get_judicial_system_and_vacancies",
    "court structure": "get_judicial_system_and_vacancies",
    "vacant positions in judiciary": "get_judicial_system_and_vacancies",
    "judicial hierarchy": "get_judicial_system_and_vacancies",
    "court system organization": "get_judicial_system_and_vacancies",
    "judiciary job openings": "get_judicial_system_and_vacancies",
    "legal system structure": "get_judicial_system_and_vacancies",
    "judicial appointments": "get_judicial_system_and_vacancies",
    "court vacancy information": "get_judicial_system_and_vacancies",
    "judicial branch positions": "get_judicial_system_and_vacancies",
    "court system vacancies": "get_judicial_system_and_vacancies",
    "judiciary employment opportunities": "get_judicial_system_and_vacancies",
    "legal system job openings": "get_judicial_system_and_vacancies",
    "judicial system career opportunities": "get_judicial_system_and_vacancies",
    "court administration vacancies": "get_judicial_system_and_vacancies",
    "judicial branch structure": "get_judicial_system_and_vacancies",
    "legal system job vacancies": "get_judicial_system_and_vacancies",
    "judiciary organizational structure": "get_judicial_system_and_vacancies",
    "court system employment": "get_judicial_system_and_vacancies",

    # get_judicial_system_info
    "judicial system overview": "get_judicial_system_info",
    "steps to become a judge": "get_judicial_system_info",
    "judicial appointments process": "get_judicial_system_info",
    "judicial eligibility criteria": "get_judicial_system_info",
    "court system explanation": "get_judicial_system_info",
    "becoming a judge guide": "get_judicial_system_info",
    "judicial career path": "get_judicial_system_info",
    "judge selection process": "get_judicial_system_info",
    "judiciary structure overview": "get_judicial_system_info",
    "legal system hierarchy": "get_judicial_system_info",
    "court levels explanation": "get_judicial_system_info",
    "judicial appointment criteria": "get_judicial_system_info",
    "judge qualification requirements": "get_judicial_system_info",
    "judicial system organization": "get_judicial_system_info",
    "court system roles": "get_judicial_system_info",
    "judicial branch overview": "get_judicial_system_info",
    "legal profession in judiciary": "get_judicial_system_info",
    "judicial system career guide": "get_judicial_system_info",
    "court administration overview": "get_judicial_system_info",
    "judicial system functionalities": "get_judicial_system_info",

    # get_ecourts_info
    "ecourts project": "get_ecourts_info",
    "ecourts services": "get_ecourts_info",
    "efiling and epayment guidelines": "get_ecourts_info",
    "case management through ecourts": "get_ecourts_info",
    "digital courts information": "get_ecourts_info",
    "online court services": "get_ecourts_info",
    "electronic court system": "get_ecourts_info",
    "ecourts project details": "get_ecourts_info",
    "digital justice system": "get_ecourts_info",
    "court digitization program": "get_ecourts_info",
    "ecourts implementation": "get_ecourts_info",
    "online case filing system": "get_ecourts_info",
    "electronic court payments": "get_ecourts_info",
    "digital case management": "get_ecourts_info",
    "ecourts modernization project": "get_ecourts_info",
    "virtual court services": "get_ecourts_info",
    "ecourts features and benefits": "get_ecourts_info",
    "online judicial services": "get_ecourts_info",
    "court process automation": "get_ecourts_info",
    "ecourts user guide": "get_ecourts_info",

    # get_ecourts_app_info
    "ecourts app": "get_ecourts_app_info",
    "ecourts mobile app": "get_ecourts_app_info",
    "ecourts mission mode project": "get_ecourts_app_info",
    "ecourts app features": "get_ecourts_app_info",
    "mobile court services": "get_ecourts_app_info",
    "digital court access": "get_ecourts_app_info",
    "ecourts app user guide": "get_ecourts_app_info",
    "court services on mobile": "get_ecourts_app_info",
    "ecourts app functionality": "get_ecourts_app_info",
    "mobile case status check": "get_ecourts_app_info",
    "ecourts app download": "get_ecourts_app_info",
    "digital court case tracking": "get_ecourts_app_info",
    "ecourts mobile services": "get_ecourts_app_info",
    "court information on smartphone": "get_ecourts_app_info",
    "ecourts app benefits": "get_ecourts_app_info",
    "mobile judicial services": "get_ecourts_app_info",
    "ecourts app setup guide": "get_ecourts_app_info",
    "smartphone court access": "get_ecourts_app_info",
    "ecourts mobile platform": "get_ecourts_app_info",
    "digital court case management": "get_ecourts_app_info",

    # get_judgment_search_and_fast_track_info
    "judgment search": "get_judgment_search_and_fast_track_info",
    "fast track courts": "get_judgment_search_and_fast_track_info",
    "special courts": "get_judgment_search_and_fast_track_info",
    "judgment search feature": "get_judgment_search_and_fast_track_info",
    "court verdict search": "get_judgment_search_and_fast_track_info",
    "expedited court proceedings": "get_judgment_search_and_fast_track_info",
    "legal decision database": "get_judgment_search_and_fast_track_info",
    "fast track justice system": "get_judgment_search_and_fast_track_info",
    "case law search tool": "get_judgment_search_and_fast_track_info",
    "accelerated court process": "get_judgment_search_and_fast_track_info",
    "judicial ruling lookup": "get_judgment_search_and_fast_track_info",
    "rapid resolution courts": "get_judgment_search_and_fast_track_info",
    "court order search system": "get_judgment_search_and_fast_track_info",
    "specialized court information": "get_judgment_search_and_fast_track_info",
    "legal precedent search": "get_judgment_search_and_fast_track_info",
    "swift justice mechanisms": "get_judgment_search_and_fast_track_info",
    "court decision archive": "get_judgment_search_and_fast_track_info",
    "expedited legal proceedings": "get_judgment_search_and_fast_track_info",
    "judgment database access": "get_judgment_search_and_fast_track_info",
    "fast-tracked legal cases": "get_judgment_search_and_fast_track_info",

    # get_efiling_and_fast_track_info
    "efiling system": "get_efiling_and_fast_track_info",
    "fast track court procedures": "get_efiling_and_fast_track_info",
    "e-filing initiatives": "get_efiling_and_fast_track_info",
    "departmental e-filing details": "get_efiling_and_fast_track_info",
    "online case filing": "get_efiling_and_fast_track_info",
    "expedited court processes": "get_efiling_and_fast_track_info",
    "digital court document submission": "get_efiling_and_fast_track_info",
    "rapid case resolution courts": "get_efiling_and_fast_track_info",
    "electronic legal filing": "get_efiling_and_fast_track_info",
    "accelerated judicial procedures": "get_efiling_and_fast_track_info",
    "court e-filing guidelines": "get_efiling_and_fast_track_info",
    "swift justice mechanisms": "get_efiling_and_fast_track_info",
    "online legal document submission": "get_efiling_and_fast_track_info",
    "fast-tracked court cases": "get_efiling_and_fast_track_info",
    "digital court filing system": "get_efiling_and_fast_track_info",
    "expedited legal proceedings": "get_efiling_and_fast_track_info",
    "e-courts filing procedures": "get_efiling_and_fast_track_info",
    "rapid dispute resolution courts": "get_efiling_and_fast_track_info",
    "electronic case initiation": "get_efiling_and_fast_track_info",
    "streamlined court processes": "get_efiling_and_fast_track_info",

    # get_telelaw_services_info
    "telelaw services": "get_telelaw_services_info",
    "telelaw accessibility": "get_telelaw_services_info",
    "legal aid through telelaw": "get_telelaw_services_info",
    "remote legal consultations": "get_telelaw_services_info",
    "virtual legal assistance": "get_telelaw_services_info",
    "online legal advice services": "get_telelaw_services_info",
    "digital legal aid platform": "get_telelaw_services_info",
    "telelaw consultation process": "get_telelaw_services_info",
    "remote legal support": "get_telelaw_services_info",
    "tele-legal services access": "get_telelaw_services_info",
    "virtual law clinics": "get_telelaw_services_info",
    "distance legal counseling": "get_telelaw_services_info",
    "telelaw program information": "get_telelaw_services_info",
    "online legal guidance": "get_telelaw_services_info",
    "remote access to legal help": "get_telelaw_services_info",
    "telelaw service availability": "get_telelaw_services_info",
    "digital legal consultation": "get_telelaw_services_info",
    "telelaw assistance programs": "get_telelaw_services_info",
    "virtual legal aid services": "get_telelaw_services_info",
    "remote legal advice system": "get_telelaw_services_info",

    # get_traffic_fine_procedures_info
    "traffic fine procedures": "get_traffic_fine_procedures_info",
    "contesting traffic fines": "get_traffic_fine_procedures_info",
    "contest traffic fine violation": "get_traffic_fine_procedures_info",

    "consequences of not paying traffic fines": "get_traffic_fine_procedures_info",
    "traffic violation steps": "get_traffic_fine_procedures_info",
    "traffic ticket payment process": "get_traffic_fine_procedures_info",
    "disputing traffic violations": "get_traffic_fine_procedures_info",
    "traffic fine appeal process": "get_traffic_fine_procedures_info",
    "traffic penalty resolution": "get_traffic_fine_procedures_info",
    "traffic citation procedures": "get_traffic_fine_procedures_info",
    "traffic fine payment options": "get_traffic_fine_procedures_info",
    "challenging traffic tickets": "get_traffic_fine_procedures_info",
    "traffic violation consequences": "get_traffic_fine_procedures_info",
    "traffic fine dispute resolution": "get_traffic_fine_procedures_info",
    "traffic offense procedures": "get_traffic_fine_procedures_info",
    "traffic ticket contestation": "get_traffic_fine_procedures_info",
    "traffic fine legal process": "get_traffic_fine_procedures_info",
    "traffic violation appeal steps": "get_traffic_fine_procedures_info",
    "traffic penalty payment methods": "get_traffic_fine_procedures_info",
    "traffic fine adjudication process": "get_traffic_fine_procedures_info",
    "traffic ticket resolution procedures": "get_traffic_fine_procedures_info",

        # get_court_live_stream_info (continued)
    "court live streaming": "get_court_live_stream_info",
    "court live stream links": "get_court_live_stream_info",
    "supreme court live streaming": "get_court_live_stream_info",
    "high court live streaming": "get_court_live_stream_info",
    "online court proceedings": "get_court_live_stream_info",
    "virtual court attendance": "get_court_live_stream_info",
    "live court case broadcasts": "get_court_live_stream_info",
    "digital court viewing": "get_court_live_stream_info",
    "real-time court sessions": "get_court_live_stream_info",
    "streaming judicial proceedings": "get_court_live_stream_info",
    "remote court hearing access": "get_court_live_stream_info",
    "live court case viewing": "get_court_live_stream_info",
    "online judicial proceedings": "get_court_live_stream_info",
    "court case live feed": "get_court_live_stream_info",
    "virtual courtroom access": "get_court_live_stream_info",
    "live streaming court cases": "get_court_live_stream_info",
    "digital court attendance": "get_court_live_stream_info",
    "real-time legal proceedings": "get_court_live_stream_info",
    "court hearing live stream": "get_court_live_stream_info",
    "online access to court sessions": "get_court_live_stream_info",

    # get_rti_and_financial_assistance_info
    "rti information": "get_rti_and_financial_assistance_info",
    "financial assistance for legal cases": "get_rti_and_financial_assistance_info",
    "rti application process": "get_rti_and_financial_assistance_info",
    "legal financial assistance": "get_rti_and_financial_assistance_info",
    "right to information details": "get_rti_and_financial_assistance_info",
    "legal case funding support": "get_rti_and_financial_assistance_info",
    "rti filing procedure": "get_rti_and_financial_assistance_info",
    "court case financial aid": "get_rti_and_financial_assistance_info",
    "transparency law information": "get_rti_and_financial_assistance_info",
    "litigation cost assistance": "get_rti_and_financial_assistance_info",
    "rti request guidelines": "get_rti_and_financial_assistance_info",
    "legal proceedings funding": "get_rti_and_financial_assistance_info",
    "information access rights": "get_rti_and_financial_assistance_info",
    "judicial financial support": "get_rti_and_financial_assistance_info",
    "rti act implementation": "get_rti_and_financial_assistance_info",
    "legal case monetary aid": "get_rti_and_financial_assistance_info",
    "government information requests": "get_rti_and_financial_assistance_info",
    "court fee assistance programs": "get_rti_and_financial_assistance_info",
    "rti compliance information": "get_rti_and_financial_assistance_info",
    "litigation expense support": "get_rti_and_financial_assistance_info",

    # get_judicial_reform_info
    "how to become a judge": "get_judicial_system_info",
    "ecourts initiatives": "get_ecourts_info",
    "judicial system overview": "get_judicial_system_and_vacancies",
    "traffic violation fines": "get_traffic_violation_payments",
    "statistical data on cases": "get_case_statistics",
    "assistant counsel responsibilities": "get_cases_info",
    "roles of assistant counsels": "get_cases_info",
    "judicial reforms": "get_judicial_reform_info",
    "specific case details": "get_cases_info",
    "case progress": "get_cases_info",
    "backlog of pending cases": "get_coram_wise_pending_cases",
    "last month case filings": "get_instituted_last_month_cases",
    "recently filed cases": "get_instituted_last_month_cases",    
    "national judicial reforms": "get_judicial_reform_info",
    "judicial reform initiatives": "get_judicial_reform_info",
    "steps for judicial reform": "get_judicial_reform_info",
    "court system improvements": "get_judicial_reform_info",
    "legal system modernization": "get_judicial_reform_info",
    "judiciary enhancement programs": "get_judicial_reform_info",
    "justice delivery reforms": "get_judicial_reform_info",
    "court process improvements": "get_judicial_reform_info",
    "judicial efficiency measures": "get_judicial_reform_info",
    "legal framework updates": "get_judicial_reform_info",
    "court modernization projects": "get_judicial_reform_info",
    "judicial system upgrades": "get_judicial_reform_info",
    "legal process streamlining": "get_judicial_reform_info",
    "court administration reforms": "get_judicial_reform_info",
    "justice system enhancements": "get_judicial_reform_info",
    "judicial infrastructure development": "get_judicial_reform_info",
    "legal procedure reforms": "get_judicial_reform_info",
    "court case management improvements": "get_judicial_reform_info",
    "judicial accountability measures": "get_judicial_reform_info"
}
